name: Continuous Integration

on:
  pull_request:
  push:
    branches:
      - '*' 

jobs:
  continuous-integration:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'adopt'

      - name: Build
        run: mvn clean install

      - name: Start Application
        run: |
          nohup mvn spring-boot:run > application.log 2>&1 &  # Inicia a aplicação e salva logs
          for i in {1..10}; do
            if curl --silent http://localhost:8080; then
              echo "Application is up!"
              break
            fi
            echo "Waiting for the application to start..."
            sleep 5
          done

      - name: Run Tests
        run: mvn test # Roda os testes que acessam localhost:8080
        env:
          BASE_URL: "http://localhost:8080" # Usa a URL base correta nos testes

  deploy:
    runs-on: ubuntu-latest
    needs: continuous-integration
    if: success()

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'adopt'

      - name: Start Application for Deploy
        run: |
          nohup mvn spring-boot:run > application.log 2>&1 &
          for i in {1..10}; do
            if curl --silent http://localhost:8080; then
              echo "Application is up!"
              break
            fi
            echo "Waiting for the application to start..."
            sleep 5
          done

      - name: Run Tests for Deploy
        run: mvn test
        env:
          BASE_URL: "http://localhost:8080"

      - name: Deploy application
        run: |
          echo "Deploying application..."
          # Adicione aqui seu comando de deploy
